#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width         2
bspc config window_gap          12

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
xrandr --output Virtual1 --mode 1920x1080
vmware-user-suid-wrapper &
/usr/bin/feh --bg-fill /home/sansa/dotfiles/resources/background.png &
/home/sansa/.config/polybar/./launch.sh &
/usr/local/bin/picom &
bspc config border_width 0
wmname LG3D &
